### ISSUE TITLE
Why is the rubyracer in the Gemfile?

### ISSUE THREAD

**Issue by justin808** [nathanvda/cocoon_simple_form_demo#11]
It's not clear why we're including therubyracer in the Gemfile.

**Comment by nathanvda** [comment]
Cleaning up open tickets here. 

Sorry for not replying earlier. My main focus is (was) on the cocoon gem, less on this project (as a mere example it did not/does not have to be perfect, just demonstrate possible use). 

A long time ago `therubyracer` was the best way to get embed the V8 JavaScript interpreter into Ruby, but since a long time this is also no longer needed.
